### ISSUE TITLE
cobble/stone gens gen their original blocks when the player isnt around

### ISSUE THREAD

**Issue by majijn** [nivoridocs/flowstone#2] opened 2018-12-28 06:52 UTC
my setup is like , 20-30 blocks from my main work area, and it seems that when I go visit , stone gets transformed, but when im not around its immediate vicinity, i only get stone/cobble, I have a couple of thousands more cobble than the other blocks than I should per how I set the config, it's weird.

**Comment by majijn** [comment] 2018-12-28 15:15
made a test flatworld with water 1 block above lava, updated the water, and flew up, only when I stand close to the blocks when the change happens do they transform properly.
I bet this also means that if I set for lava to turn to magma only, I would still get obsidian when the obsidian updates occur far away enough







![2018-12-28_08 02 12](https://user-images.githubusercontent.com/18368034/50519518-a088e900-0abb-11e9-9703-f7b140d9df36.png)
![2018-12-28_08 03 08](https://user-images.githubusercontent.com/18368034/50519519-a088e900-0abb-11e9-8410-5d72e13c7453.png)
![2018-12-28_08 03 18](https://user-images.githubusercontent.com/18368034/50519520-a1217f80-0abb-11e9-8ef5-bce6272701a3.png)
![2018-12-28_08 03 25](https://user-images.githubusercontent.com/18368034/50519521-a1217f80-0abb-11e9-878d-0d3e7e5c21a1.png)
![2018-12-28_08 03 38](https://user-images.githubusercontent.com/18368034/50519522-a1217f80-0abb-11e9-992e-b2136bc71f1e.png)
![2018-12-28_08 03 53](https://user-images.githubusercontent.com/18368034/50519523-a1ba1600-0abb-11e9-8f23-3d3a66bc7607.png)

**Comment by nivoridocs** [comment] 2018-12-28 15:40
I know what the problem is, the event that triggers the block changing effect is related to the sound system (I know, that's weird!), so when there is no player nearby the sound event isn't fired, and then the block doesn't change. I'll try to fix it, but it will be hard.

**Comment by nivoridocs** [comment] 2020-10-16 19:17
Fixed in v1.1.0

**Closed by nivoridocs** 2020-10-16 19:17 UTC
